--- # webserver
server:
  port: 8088
  servlet:
    context-path: /
    session:
      timeout: 1800s

--- # logging
logging:
  level:
    root: INFO #DEBUG #TARCE < DEBUG < INFO < WARN < ERROR < FATAL

#    org.springframework.web.servlet.mvc: debug
#    org.mybatis: debug

--- # datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ivg?zeroDateTimeBehavior=convertToNull&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 666666
    #url: jdbc:mysql://127.0.0.1:8306/ivg?zeroDateTimeBehavior=convertToNull&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    #username: root
    #password: ukim666666
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    enabled: false
    default-domain: [App]
--- # MVC
mvc:
  view:
    prefix: /templates/
    suffix: .html
  static-path-pattern: /**

--- # template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

--- # caching
spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml

--- # mybatis
mybatis:
  config-location: classpath:mybatis-config.xml #增加mybatis xml风格的支挿
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cn.uk.model

--- #配置Linux下XML存储路径夿
linux:
  xml:
    urlHear: /home/uk9101/XML   #/home/uk9100/XML
    ipServer: http://172.18.44.111/IGApi/ #http://172.18.44.107/IGApi


--- #配置门禁系统相关
##ip: 192.168.10.2
##port: 8901
dooraccess:
  ip: 127.0.0.1
  port: 8080
  photoPort: 9012
  apiBaseUrl: http://192.168.10.100:8091/api
  userName: 9999
  passWord: 123456
  allow: true

--- #与智能网关c++部门通信配置
smartgateway:
  ip: 127.0.0.1
  port: 7700
  allow: true


doorEntrance_test:
  port: 8901
east-round_test:
  port: 8905

--- #进行图片访问(本地)
getchildstation:
  ip: 10.144.66.41
  port: 8186
  test_url: http://10.144.66.41:8186/data/task/202006/20200630102424398/线路PT气室鱼眼%23340/pic.jpg

--- #朗驰webservice服务端地址
launwebservice:
  ip: http://192.168.16.23
  port: 18888
  childUrl: /ws/pasService?wsdl
  enabled: false

--- #鲁能webservice服务端地址
###/SubstationService/soap/substationPlatform?wsdl
lunengwebservice:
  ip: http://192.168.1.10
  port: 8081
  childUrl: /SubstationService/soap/substationPlatform?wsdl
  enabled: true
